swagger: '2.0'
info:
  description: |
    Component Pipeline REST Scaffold
  version: 1.0.0
  title: Component Pipeline REST Scaffold
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: 127.0.0.1:3000
basePath: /api/v1
schemes:
 - http
 - https
consumes:
  - application/json
produces:
  - application/json
tags:
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
paths:
  /register:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done a non-logged-in user.
      operationId: createUser
      parameters:
      - in: body
        name: body
        description: Created user object
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
    xml:
      name: User
