swagger: '2.0'
info:
  version: '0.0.1'
  title: 'Collection-Pipeline-REST-Scaffold'
  description: 'REST API Scaffold'
host: 127.0.0.1:3000
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
schemes:
 - http
tags:
  - name: Users
    description: Simple user endpoints
  - name: Specification
    description: The swagger API specification

definitions:
  UserBody:
    type: object
    title: user
    required:
      - id
      - name
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: username

paths:
  /user:
    get:
      tags:
        - Users
      description: Fetch all users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new user
      parameters:
        - name: user
          in: body
          description: a user
          required: true
          schema: 
            $ref: "#/definitions/UserBody"
      responses:
        200:
          description: Returns all users
  
  /user/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          type: integer
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: User not found
  
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
